services:
  frontend:
    ports:
      - "8080:80"
    build:
      context: ./frontend
      target: production
    env_file:
      - ./frontend/.env.production
  users:
    image: users-service:prod
    ports:
      - "8001:80"
    build:
      context: ./services/users
    env_file:
      - ./services/.env.production
  appliances:
    image: appliances-service:prod
    ports:
      - "8002:80"
    build:
      context: ./services/appliances
    env_file:
      - ./services/.env.production
