services:
  users:
    image: users-service:dev
    command: "fastapi dev app/main.py --host 0.0.0.0"
    ports:
      - "8001:8000"
    build:
      context: ./services/users
    env_file:
      - ./services/.env
    volumes:
      - ./services/users/app:/code/app
  appliances:
    image: appliances-service:dev
    command: "fastapi dev app/main.py --host 0.0.0.0"
    ports:
      - "8002:8000"
    build:
      context: ./services/appliances
    env_file:
      - ./services/.env
    volumes:
      - ./services/appliances/app:/code/app
    depends_on:
      - users
  fire_safety:
    image: fire-safety-service:dev
    command: "fastapi dev app/main.py --host 0.0.0.0"
    ports:
      - "8003:8000"
    build:
      context: ./services/fire_safety
    env_file:
      - ./services/.env
    environment:
      - APPLIANCES_SERVICE_URL=http://appliances:8000
    volumes:
      - ./services/fire_safety/app:/code/app
    depends_on:
      - appliances
  energy:
    image: energy-service:dev
    command: "fastapi dev app/main.py --host 0.0.0.0"
    ports:
      - "8004:8000"
    build:
      context: ./services/energy
    env_file:
      - ./services/.env
    environment:
      - APPLIANCES_SERVICE_URL=http://appliances:8000
    volumes:
      - ./services/energy/app:/code/app
    depends_on:
      - appliances
  security_monitoring:
    image: security-monitoring-service:dev
    command: "fastapi dev app/main.py --host 0.0.0.0"
    ports:
      - "8006:8000"
    build:
      context: ./services/security_monitoring
    env_file:
      - ./services/.env
    environment:
      - SECURITY_SERVICE_URL=http://security_monitoring:8000
    volumes:
      - ./services/security/app:/code/app
    depends_on:
      - appliances

